language: node_js
node_js:
  - "9"

install:
  - echo "const apiPrefix = {" > config.js
  - echo "  server:'$ANIMELOOP_API_URL'," >> config.js
  - echo "  browser:'$ANIMELOOP_API_URL'," >> config.js
  - echo "};" >> config.js
  - echo "" >> config.js
  - echo "export default apiPrefix" >> config.js
  - yarn install

script:
  - yarn build
